// <auto-generated />
using System;
using MINICORE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MINICORE.Migrations
{
    [DbContext(typeof(minicore))]
    [Migration("20251021213912_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MINICORE.Models.ComitionRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CommissionPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MinimumAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Reglas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommissionPercentage = 5m,
                            MinimumAmount = 0m
                        },
                        new
                        {
                            Id = 2,
                            CommissionPercentage = 7.5m,
                            MinimumAmount = 10000m
                        },
                        new
                        {
                            Id = 3,
                            CommissionPercentage = 10m,
                            MinimumAmount = 50000m
                        },
                        new
                        {
                            Id = 4,
                            CommissionPercentage = 12.5m,
                            MinimumAmount = 100000m
                        });
                });

            modelBuilder.Entity("MINICORE.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.ToTable("Ventas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 15000m,
                            SaleDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 25000m,
                            SaleDate = new DateTime(2025, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 80000m,
                            SaleDate = new DateTime(2025, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 2
                        },
                        new
                        {
                            Id = 4,
                            Amount = 45000m,
                            SaleDate = new DateTime(2025, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 2
                        },
                        new
                        {
                            Id = 5,
                            Amount = 120000m,
                            SaleDate = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SellerId = 3
                        });
                });

            modelBuilder.Entity("MINICORE.Models.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Vendedores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Juan Pérez"
                        },
                        new
                        {
                            Id = 2,
                            Name = "María González"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Carlos Ramírez"
                        });
                });

            modelBuilder.Entity("MINICORE.Models.Sale", b =>
                {
                    b.HasOne("MINICORE.Models.Seller", "Seller")
                        .WithMany("Sales")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("MINICORE.Models.Seller", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
